# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-01 08:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hood', '0005_join_social_ammenities'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Social_Ammenities',
            new_name='Social_Amenities',
        ),
    ]
